eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://54.157.144.47:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://54.157.144.47:8081/
          predicates:
            - Path=/todo-service/**
